spring:
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue:
            org.hibernate.dialect.MySQL5InnoDBDialect
          storage_engine: innodb
        show_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  profiles:
    include:
      - oauth