spring:
  profiles:
    include: ec2, oauth, ec2-db, jwt
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue:
            org.hibernate.dialect.MySQL5InnoDBDialect
          storage_engine: innodb
        default_batch_fetch_size: 1000
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always